### ISSUE TITLE
Fishing Rod not working either doing anything...

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#147]
Fishing Rod is not working, just plays the sound. i wish that IT worked and someone made that plugin that with the Fishing you could do like Spiderman, but in here it cant happend, nothing happends after trying to use the rod,

**Comment by thebigsmileXD** [comment]
Its work in progress. We just don't know the package

**Comment by TheKillerTacos** [comment]
ok, should i close this issue, or youll use it as a TODO?

**Comment by Adam1609** [comment]
Todo should be perfect

**Comment by thebigsmileXD** [comment]
You now can fish. But because theres no rope yet, you get a popup "A fish bites!".. A bit basic, but better than nothing!
Also you can reel the rod.
Fishing is really basic. It just randoms through the 4 fish types.
You get exp for caughing a fish.
It cant pull entities to you or knockback them back.

**Comment by robske110** [comment]
Dan, Icould you add translation for that a fish bites

**Comment by thebigsmileXD** [comment]
Not needed, due its temporary.

**Comment by TheKillerTacos** [comment]
Yay

**Comment by thebigsmileXD** [comment]
I'll close this for now. We don't know the methods to generate the line.

I'll add loot tables later.
