### ISSUE TITLE
0.14.0 cannot join

### ISSUE THREAD

**Issue by Driesboy** [ClearSkyTeam/ClearSky#184]

**Comment by thebigsmileXD** [comment]
Latest phar, disabled CustomAlerts message?

**Comment by XxDXM-hippiexX** [comment]
Do you have a pc map as your lobby? pc maps dont work anymore i dont think /: same was happening to me i would crash if i warped from another world to my pc map or just couldnt join if i was joining in the pc world.

**Comment by TheKillerTacos** [comment]
Im using a PC Map, since build #14 from 0.14.0, now using latest and still no Problems, check if your world isnt corrupted, delete pocketmine.yml if havent, and check if any firewall is blocking the ports of your server, try joining to your server, if it doesnt work, try re-downloading everything again.

**Comment by MCPEPIG** [comment]
It's fixed.

**Comment by TheKillerTacos** [comment]
Then Someone close this issue
