### ISSUE TITLE
php 7 to 0.14

### ISSUE THREAD

**Issue by BlackSiDe62** [ClearSkyTeam/ClearSky#189]
Please update php7 core to 0.14.0

**Comment by robske110** [comment]
We are to very focused on php7 yet, however you can download the master phar and use it on an php7 binary too!

**Comment by aodzip** [comment]
@robske110 That can lead a crash lol

**Comment by robske110** [comment]
Oh forgot about Int Enum String stuff

**Comment by MasterWolf** [comment]
no plz dont update. if you want to update, create branch. I hate php7

**Comment by robske110** [comment]
Lol you shouldn't hate it

**Comment by GreenNature-MC-Server** [comment]
@MasterWolf I hate php7 too and because nobody of us can php we must use ClearSky since the 0.14.0 Update! (Many plugins are incompatible)

Thanks a lot for make ImagicalMine php7 only! That's why many server owners who don't can php7 (That's more of 95% of all Server Owners) must use ClearSky now!

If ImagicalMine will be available on php5 again i will like and use ImagicalMine again!

**Comment by XShockinFireX** [comment]
Ikr i stopped using ImagicalMine because it only supports php7 now
