### ISSUE TITLE
Players timing out

### ISSUE THREAD

**Issue by SavionLegendZzz** [ClearSkyTeam/ClearSky#654]
Players on my server will time out randomly can you please fix this

**Comment by SalmonGER** [comment]
How much packet loss do your pocketmine.yml accept?

**Comment by thebigsmileXD** [comment]
@SalmonGER Great answer, correct point.

**Comment by SavionLegendZzz** [comment]
The normal setting

**Comment by Aericio** [comment]
Oh this happens to me also :-1:

**Comment by robske110** [comment]
This is network related and or player related.
These things can happen (fix in these thingies)
1. Real network lag either on your side OR THE PLAYER'S side (set network.timeout value HIGHER)
2. Bad network either on your side OR THE PLAYER'S side (set network.acceptable-packetlost HIGHER)
3. Overloaded network upload on your side (set network.batch-threshold to 64 and set network.compression-level to 9)
4. Overloaded network wich is not your upload, maybe your Player's upload/download. That your download fails is very unlikely and you can't do anything against this.
5. Player's client crash. Temporarily reset all your worlds, does this still happen so often? Because if not, your worlds contain unknown Blocks, wich crash the client.
