### ISSUE TITLE
Always Spawning at spawn on join

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#693]

**Comment by robske110** [comment]
This issue exists since ages...

**Comment by kam187** [comment]
Kam ., [29.08.16 11:36]
ok well the fix for #693 is in player.php

Kam ., [29.08.16 11:36]
line 1853

Player.php

-    if(($level = $this->server->getLevelByName($nbt["Level"])) === null or $this->isAlive()){
+    if(($level = $this->server->getLevelByName($nbt["Level"])) === null){

can someone commit it, tested already.  I don't have time to make a pull request etc and it won't let me commit directly.
