### ISSUE TITLE
New Server Issues (May be operator error)

### ISSUE THREAD

**Issue by joshdcollins** [ClearSkyTeam/ClearSky#739]
I could not find a ClearSky friendly forum - if this issue log is not an appropriate place for these questions, apologies.  Please redirect me.

I've set up a ClearSky server running ClearSky version 1.1-php7 "DarkSunset" (API 2.0.0) Build 377 on MacOS Sierra.

I'm connecting with Minecraft PE (on iphone and ipad) v0.15.9.

I'm seeing the following 3 issues while testing this before letting loose my kid on it:
- Hunger does not seem to deplete or is doing so at a very slow rate.  In pocketmine.yml (attached) hunger is set to true.
- I'm seeing nothing spawn (mobs, animals, etc.).  I've moved between several biomes over several MC days and nothing
- Sometimes blocks appear to be broken, but reappear if the block is not held down for a second longer (to the point it 'explodes') -- this is just something it took a moment to get used to

I would appreciate any feedback on how to resolve these items.

Thanks!
jc

[pocketmine.yml.txt]

(https://github.com/ClearSkyTeam/ClearSky/files/497975/pocketmine.yml.txt)

**Comment by caspervanneck** [comment]
There is no mobai yet

**Comment by thebigsmileXD** [comment]
The hunger depletion is like in vanilla MCPE. The (hunger) settings in the pocketmine.yml are soon deprecated.
Spawning of animals is "implemented" into the AsyncAI2 branch. Its in rewrite though. Due to bugged light calculation and other limitations its not acurrate. You can download plugins instead. (MyOwnWorld, EntityManager, ArtificalIntelligence. Read in other issues for that.)
If i understand that block breaking stuff correctly, i can just crush it down to server lags or network lags.
Maybe Timings could help.

Thanks for the detailed device and build informations!

**Comment by joshdcollins** [comment]
Awesome, thank you for your responses -- I'm new to the MCPE server scene and will dig into some of the plugins and tune some of the network settings.

**Comment by robske110** [comment]
network settings - should be self explanatory: I assume you have enough cpu availible so just set that compression setting to 9 (async compression is recommended)
Animal spawn&animalAI - we may implement animal spawning just for a better survival experience, they won't move though.
